export enum ErrorCode {
    UNKNOWN_ERROR = 0,
    USER_NOT_EXIST_ERROR = 1,
    USER_EXIST_ERROR = 2,
    WRONG_PASSWORD_ERROR = 3,
    REQUEST_NOT_FOUND_ERROR = 4,
    TOKEN_VERIFY_ERROR = 5,
    COURSE_NOT_EXIST_ERROR = 6,
    POST_NOT_EXIST_ERROR = 7,
    INVALID_ACCESS_ERROR = 8,
    TEACHER_NOT_EXIST_ERROR = 9,
    COMMENT_NOT_EXIST_ERROR = 10,
  }
  