export enum ErrorCode {
    UNKNOWN_ERROR = 0,
    USER_NOT_EXIST_ERROR = 1,
    USER_EXIST_ERROR = 2,
    WRONG_PASSWORD_ERROR = 3,
    REQUEST_NOT_FOUND_ERROR = 4,
    TOKEN_VERIFY_ERROR = 5,
    COURSE_NOT_EXIST_ERROR = 6,
    USER_POSTED_COURSE_ERROR = 7,
    COURSE_EXIST_ERROR = 8,
    POST_NOT_EXIST_ERROR = 9,
    INVALID_ACCESS_ERROR = 10,
    TEACHER_NOT_EXIST_ERROR = 11,
    TEACHER_EXIST_ERROR = 12,
    COMMENT_NOT_EXIST_ERROR = 13,
    JSON_ERROR = 14,
    FILE_NOT_FOUND_ERROR = 15,
  }
  