<template>
    <div class="CourseListContain">

        <div class="courseType">
            <CourseType/>
        </div>
        <div v-for="course in courses" :key="course.id">
        <CourseItem
            :id="course.id"
            :title="course.title"
            :teacher="course.teacher"
            :year="course.year"
            :courseRate="course.rate"
            :raterCount="course.raterCount"
            :difficulty="course.difficulty"
            :workload="course.workload"
            :grading="course.grading"
            :gain="course.gain"
        />
        </div>
        <Pagination/>
    </div>
</template>

<script lang="ts" setup name="">
    import { ref } from 'vue'
    import CourseType from '@/components/course/CourseType.vue'
    import CourseItem from '@/components/course/CourseItem.vue';
    import Pagination from '@/utils/Pagination.vue';
    import Header from '@/components/header/Header.vue';

    const courses = ref([
    {
        id: 1,
        title: '工科数学分析(1)',
        teacher: '孙玉泉',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 2,
        title: '工科数学分析(2)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 3,
        title: '工科高等代数',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 4,
        title: '概率统计 A',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 5,
        title: '基础物理学(信息类)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 6,
        title: '工科大学物理(2)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 7,
        title: '程序设计基础',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 8,
        title: '离散数学(信息类)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 9,
        title: '数据结构与程序设计(信息类)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 10,
        title: '大学英语 A(1)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 11,
        title: '大学英语 A(2)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 12,
        title: '思想道德与法治',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 13,
        title: '形势与政策(1)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 14,
        title: '军事理论',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 15,
        title: '体育(1)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 16,
        title: '体育(2)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 17,
        title: '体育(3)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 18,
        title: '体育(4)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 19,
        title: '体育(5)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 20,
        title: '体育(6)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 21,
        title: '体质健康标准测试',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 22,
        title: '素质教育(博雅课程)(1)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 23,
        title: '素质教育(博雅课程)(2)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 24,
        title: '素质教育(博雅课程)(3)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 25,
        title: '素质教育(博雅课程)(4)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 26,
        title: '素质教育(博雅课程)(5)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 27,
        title: '素质教育(博雅课程)(6)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 28,
        title: '素质教育(博雅课程)(7)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 29,
        title: '素质教育(博雅课程)(8)',
        teacher: '李四',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    },
    {
        id: 30,
        title: '心理健康(1)',
        teacher: '张三',
        year: '2023春',
        rate: 4.2,
        raterCount: 1500,
        difficulty: '较难',
        workload: '适中',
        grading: '中等',
        gain: '较大',
    }
    ]);

</script>

<style scoped lang="css">
    .CourseListContain {
        width: 80%;
        margin-top: 30px;
        margin-bottom: 50px;
        margin-left: auto;
        margin-right: auto;
    }
</style>
